### ISSUE TITLE
CSV export link

### ISSUE THREAD

**Issue by Jamalnaserhasan** [leewillis77/WpListTableExportable#3]
Hi @leewillis77 , I need to change CSV export link to be available for every one to download or to send at emails , or by another meaning I need to upload file to wordpress media library , How can we achieve that ?

**Comment by leewillis77** [comment]
Hi; 

This library is simply aimed at making list-tables exportable by users viewing them. It's not designed as a general purpose CSV export tool. While I'm not 100% sure what you're asking for here, I'm fairly confident that this isn't the right library for the job. It sounds like you need something custom built to meet your needs.
